import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { ChangeEvent, ChangeEventHandler, useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [input, setInput] = useState("");
  const [referrer, setReferrer] = useState("");
  const [output, setOutput] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      let url = "/api/hello";
      let ref = referrer?.trim() ?? "";
      if (ref != "") {
        url = url + `?referrer=${ref}`;
      }
      var result = await fetch(url, { body: input, method: "POST" });
      var body = await result.text();
      setOutput(body);
      setIsLoading(false);
    };

    setIsLoading(true);
    fetchData().catch((e) => {
      setIsLoading(false);
      console.error(e);
    });
  }, [input, referrer]);

  const processInput = (input: ChangeEvent<HTMLTextAreaElement>) => {
    let val = input.target.value;
    setInput(val);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ width: "100%" }}>
          <label>Urls, one per line:</label>
          <div style={{ width: "100%" }}>
            <textarea
              name="keymap_input"
              id="keymap_input"
              cols={30}
              rows={10}
              style={{ width: "100%" }}
              value={input}
              onChange={processInput}
            ></textarea>
          </div>
        </div>

        <div style={{ width: "100%" }}>
          <label>Referrer (optional):</label>
          <input
            type="text"
            placeholder="referrer"
            value={referrer}
            onChange={(c) => setReferrer(c.target.value)}
            style={{ width: "100%" }}
          ></input>
        </div>

        <div>
          <label>
            Output to embed:
            <span style={{display: isLoading?"initial":"none"}}>
    (loading)
            </span>
          </label>
        </div>
        <div className={styles.mainoutput}>
          <textarea
            name="keymap_input"
            id="keymap_input"
            readOnly
            cols={30}
            rows={10}
            className={styles.mainoutput}
            value={output}
          ></textarea>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
