import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ChangeEvent, ChangeEventHandler, useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");

  useEffect( ()=>{
    const fetchData = async ()=>{
      var result = await Promise.all(input.split("\n")
      .map(async s => {
        let url = s.trim();
        if(!url.startsWith("http")){
          console.warn(`Line '${url}' is not an url`);
          return "";
        }
        let result :{thumbnail_url:string, video_id:string} = (await (await fetch(`http://vimeo.com/api/oembed.json?url=${url}`)).json());
        let embedHtml=`<img class="ic-youtube" data-video="vimeo" src="${result['thumbnail_url']}" data-vimeo-id="${result['video_id']}">`
        return embedHtml;
      }));
      let val = "";
      
      
      setOutput(result.join("\n"));
    }

    fetchData().catch(console.error);
    let val = input;
    val =`Hey, val was ${val}`
    setOutput(val);
  }, [input])

    const processInput = (input:ChangeEvent<HTMLTextAreaElement>)=>{
      let val = input.target.value;
      setInput(val);
    }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <textarea
              name="keymap_input"
              id="keymap_input"
              cols={30}
              rows={10}
              className={styles.input_textarea}
              value={input}
              onChange={processInput}
            ></textarea>
          </div>
          
        </div>

        <div className={styles.center}>
        <div>
            <textarea
              name="keymap_input"
              id="keymap_input"
              readOnly
              cols={30}
              rows={10}
              className={styles.input_textarea}
              value={output}
            ></textarea>
          </div>        
        </div>

        <div className={styles.grid}>

        </div>
      </main>
    </>
  )
}
